# Generated by Django 4.2.3 on 2023-07-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_link_video_course_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=3000, verbose_name='стоимость курса'),
        ),
    ]
