# Generated by Django 4.2.3 on 2023-07-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='подписка'),
        ),
    ]
