# Generated by Django 4.2.3 on 2023-07-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paiment_intent_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID платежа в Stripe'),
        ),
    ]
