# Generated by Django 4.2.3 on 2023-07-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('lesson', '0002_lesson_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, to='course.course', verbose_name='курс'),
        ),
    ]
