# Generated by Django 4.2.3 on 2023-07-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_remove_lesson_course_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='url',
            field=models.URLField(max_length=30, verbose_name='ссылка'),
        ),
    ]
